### ISSUE TITLE
Contradictory Specification

### ISSUE THREAD

**Issue by ManuelLeitner** [rstropek-teaching/bike-rental-quiz-5ahif-ManuelLeitner#1]
> [Total costs in Euro - total rental costs, two decimal places, value >= 1.00](https://github.com/rstropek-teaching/bike-rental-quiz-5ahif-ManuelLeitner#rentals)

This is contradictory to:

> [Rental price in Euro for first hour - mandatory number, two decimal places, value >= 0.00](https://github.com/rstropek-teaching/bike-rental-quiz-5ahif-ManuelLeitner#bikes)

I assume the constraint at Rentals should be 0.
Am I right?

**Comment by rstropek** [comment]
You are right. The total costs in Euro can be 0. I will fix that in my repo. However, I can no longer change your forked repos. Sorry for my mistake.

Greetings,
Rainer Stropek.

**Comment by rstropek** [comment]
Fixed, see [this checkin](https://github.com/rstropek/htl-csharp/commit/2bdbf815e105980a5f0f1876800a36c0db79ac02#diff-174a49d6a7f7a8f5dc054a3edbae717a).

Greetings,
Rainer Stropek.
